name: Build and Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "build"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./Scripts/minify
        run: npm ci

      - name: Minify
        run: node ./Scripts/minify/minify.js

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
            path: "./Output"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
