name: Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Allow one concurrent deployment
concurrency:
  group: "build"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
          path: main
        
      - name: Checkout dist repo
        uses: actions/checkout@v3
        with:
          repository: Wade7wastaken/TrulyUnblockedGamesDist
          path: dist
          
      - name: Debug
        run: ls
      - name: Debug2
        working-directory: ./main/
        run: ls


      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        working-directory: ./main/Scripts/minify
        run: npm ci
      
      - name: Minify
        run: node ./main/Scripts/minify/minify.js

      - name: Copy contents
        run: cp -R main/Output dist

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Format files"
          default_author: github_actions
          cwd: "./dist"
